// Generated by https://quicktype.io

export interface IAzureWorkItem {
  id: number;
  rev: number;
  fields: IAzureWorkItemFields;
  url: string;
}

export interface IAzureWorkItemPost {
  project: string;
  type: string;
  title: string;
  assignee: string;
  state: string;
  area: string;
  reason: string;
  iteration: string;
  repro_steps: string;
  system_info: string;
  story_points: string;
  priority: string;
  severity: string;
  activity: string;
  original_estimate: string;
  remaining: string;
  completed: string;
  tags: string;
}

export interface IAzureWorkItemFields {
  "System.AreaPath": string;
  "System.TeamProject": string;
  "System.IterationPath": string;
  "System.WorkItemType": string;
  "System.State": string;
  "System.Reason": string;
  "System.AssignedTo": System;
  "System.CreatedDate": string;
  "System.CreatedBy": System;
  "System.ChangedDate": string;
  "System.ChangedBy": System;
  "System.CommentCount": number;
  "System.Title": string;
  "Microsoft.VSTS.Common.StateChangeDate": string;
  "Microsoft.VSTS.Common.Priority": number;
  "Microsoft.VSTS.Scheduling.TargetDate": string;
  "Microsoft.VSTS.Scheduling.StartDate": string;
  "System.Description": string;
  "System.Tags": string;
}

export interface System {
  displayName: string;
  url: string;
  _links: Links;
  id: string;
  uniqueName: string;
  imageUrl: string;
  descriptor: string;
}

export interface Links {
  avatar: Avatar;
}

export interface Avatar {
  href: string;
}
