// Generated by https://quicktype.io

export interface IAzureWorkItem {
  id: number;
  rev: number;
  fields: IAzureWorkItemFields;
  url: string;
}

export interface IAzureWorkItemPost {
  "System.TeamProject": string;
  "System.WorkItemType": string;
  "System.Title": string;
  "System.AssignedTo"?: System;
  "System.AreaPath"?: string;
  "System.Reason"?: string;
  "System.State"?: string;
  "System.IterationPath"?: string;
  "Microsoft.VSTS.Common.ValueArea"?: string;
  "Microsoft.VSTS.TCM.ReproSteps"?: string;
  "Microsoft.VSTS.TCM.SystemInfo"?: string;
  "Microsoft.VSTS.Scheduling.StoryPoints"?: string;
  "Microsoft.VSTS.Common.Priority"?: string;
  "Microsoft.VSTS.Common.Severity"?: string;
  "Microsoft.VSTS.Common.Activity"?: string;
  "Microsoft.VSTS.Scheduling.OriginalEstimate"?: string;
  "Microsoft.VSTS.Scheduling.RemainingWork"?: string;
  "Microsoft.VSTS.Scheduling.CompletedWork"?: string;
  "System.Tags"?: string;
}

export interface IAzureWorkItemFields {
  "Microsoft.VSTS.Common.ValueArea": string;
  "System.AreaPath": string;
  "System.TeamProject": string;
  "System.IterationPath": string;
  "System.WorkItemType": string;
  "System.State": string;
  "System.Reason": string;
  "System.AssignedTo": System;
  "System.CreatedDate": string;
  "System.CreatedBy": System;
  "System.ChangedDate": string;
  "System.ChangedBy": System;
  "System.CommentCount": number;
  "System.Title": string;
  "Microsoft.VSTS.Common.StateChangeDate": string;
  "Microsoft.VSTS.Common.Priority": number;
  "Microsoft.VSTS.Scheduling.FinishDate": string;
  "Microsoft.VSTS.Scheduling.TargetDate": string;
  "Microsoft.VSTS.Scheduling.StartDate": string;
  "System.Description": string;
  "System.Tags": string;
}

export interface System {
  displayName: string;
  url: string;
  _links: Links;
  id: string;
  uniqueName: string;
  imageUrl: string;
  descriptor: string;
}

export interface Links {
  avatar: Avatar;
}

export interface Avatar {
  href: string;
}

export interface IAzureWorkItemType {
  id: string;
  name: string;
  description: string;
  url: string;
  inherits: null;
  class: string;
  color: string;
  icon: string;
  isDisabled: boolean;
}
