allowBuilds:
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/fontawesome-svg-core': false
  '@parcel/watcher': false
  '@sentry/cli': false
  '@swc/core': false
  core-js: false
  esbuild: false
