const fs = require("fs");

const workItemFields1 = {
  Agile: {
    Bug: [
      "Reason",
      "Priority",
      "Severity",
      "Activity",
      "Original Estimate",
      "Remaining",
      "Completed",
      "Repro Steps",
      "System Info",
    ],
    Epic: [
      "Risk",
      "Priority",
      "Effort",
      "Business Value",
      "Time Criticality",
      "Start Date",
      "Target Date",
    ],
    Feature: [
      "Risk",
      "Priority",
      "Effort",
      "Business Value",
      "Time Criticality",
      "Start Date",
      "Target Date",
    ],
    Issue: ["Stack Rank", "Priority", "Due Date"],
    Task: [
      "Priority",
      "Activity",
      "Original Estimate",
      "Remaining",
      "Completed",
    ],
    "Test Case": ["Steps"],
    "User Story": ["Risk", "Priority", "Story Points", "Value area"],
  },
  Basic: {
    Epic: ["Priority", "Start Date", "Target Date"],
    Issue: ["Priority", "Effort"],
    Task: ["Priority", "Activity", "Remaining Work"],
  },
  Scrum: {
    Bug: [
      "Priority",
      "Severity",
      "Activity",
      "Effort",
      "Remaining Work",
      "Found in Build",
      "Integrated in Build",
      "Repro Steps",
      "System Info",
      "Acceptance Criteria",
    ],
    Epic: [
      "Priority",
      "Effort",
      "Start Date",
      "Integrated in Build",
      "Time Criticality",
      "Business Value",
      "Value Area",
      "Acceptance Criteria",
    ],
    Feature: [
      "Priority",
      "Effort",
      "Start Date",
      "Integrated in Build",
      "Time Criticality",
      "Business Value",
      "Value Area",
      "Acceptance Criteria",
    ],
    Inpediment: ["Priority", "Resolution"],
    "Product Backlog Item": [
      "Priority",
      "Effort",
      "Business Value",
      "Value Area",
      "Acceptance Criteria",
    ],
    Task: ["Priority", "Activity", "Blocked", "Remaining Work"],
    "Test Case": ["Steps"],
  },
  CMMI: {
    Bug: [
      "Resolved Reason",
      "Size",
      "Priority",
      "Triage",
      "Blocked",
      "Original Estimate",
      "Remaining Work",
      "Completed Work",
      "Discipline",
      "Root Cause",
      "Repro Steps",
      "Symptom",
      "System Info",
      "Update computer",
    ],
    "Change Request": [
      "Justification",
      "Inpact on Architecture",
      "Inpact on user experience",
      "Inpact on test",
      "Inpact on design/development",
      "Inpact on technical publications",
      "Priority",
      "Triage",
      "Blocked",
      "Integrated",
    ],
    Epic: [
      "Priority",
      "Start Date",
      "Target Date",
      "Triage",
      "Effort",
      "Business Value",
      "Time Criticality",
      "Value area",
    ],
    Feature: [
      "Priority",
      "Start Date",
      "Target Date",
      "Triage",
      "Effort",
      "Business Value",
      "Time Criticality",
      "Value area",
    ],
    "Change request": [
      "Priority",
      "Triage",
      "Escalate",
      "Original Estimate",
      "Target Resolve Date",
      "Actual Resolve Date",
    ],
    Requirement: [
      "Inpact Assessment",
      "Plan",
      "Actual Resolution",
      "Size",
      "Priority",
      "Triage",
      "Blocked",
      "Committed",
    ],
    Risk: [
      "Contingency Plan",
      "Priority",
      "Severity",
      "Blocked",
      "Original Estimate",
      "Probability",
    ],
    Task: [
      "Priority",
      "Triage",
      "Blocked",
      "Original Estimate",
      "Remaining Work",
      "Completed Work",
    ],
    "Test Case": [
      "Steps",
      "Original Estimate",
      "Remaining Work",
      "Completed Work",
      "Start Date",
      "Finish Date",
    ],
  },
};

const workItemFields2 = {
  Agile: {
    Bug: [
      "System.Reason",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Severity",
      "Microsoft.VSTS.Common.Activity",
      "Microsoft.VSTS.Scheduling.OriginalEstimate",
      "Microsoft.VSTS.Scheduling.RemainingWork",
      "Microsoft.VSTS.Scheduling.CompletedWork",
      "Microsoft.VSTS.TCM.ReproSteps",
      "Microsoft.VSTS.TCM.SystemInfo",
    ],
    Epic: [
      "Microsoft.VSTS.Common.Risk",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.Effort",
      "Microsoft.VSTS.Common.BusinessValue",
      "Microsoft.VSTS.Common.TimeCriticality",
      "Microsoft.VSTS.Scheduling.StartDate",
      "Microsoft.VSTS.Scheduling.TargetDate",
    ],
    Feature: [
      "Microsoft.VSTS.Common.Risk",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.Effort",
      "Microsoft.VSTS.Common.BusinessValue",
      "Microsoft.VSTS.Common.TimeCriticality",
      "Microsoft.VSTS.Scheduling.StartDate",
      "Microsoft.VSTS.Scheduling.TargetDate",
    ],
    Issue: [
      "Microsoft.VSTS.Common.StackRank",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.DueDate",
    ],
    Task: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Activity",
      "Microsoft.VSTS.Scheduling.OriginalEstimate",
      "Microsoft.VSTS.Scheduling.RemainingWork",
      "Microsoft.VSTS.Scheduling.CompletedWork",
    ],
    "Test Case": ["Microsoft.VSTS.TCM.ReproSteps"],
    "User Story": [
      "Microsoft.VSTS.Common.Risk",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.StoryPoints",
      "Microsoft.VSTS.Common.ValueArea",
    ],
  },
  Basic: {
    Epic: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.StartDate",
      "Microsoft.VSTS.Scheduling.TargetDate",
    ],
    Issue: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.Effort",
    ],
    Task: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Activity",
      "Microsoft.VSTS.Scheduling.RemainingWork",
    ],
  },
  Scrum: {
    Bug: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Severity",
      "Microsoft.VSTS.Common.Activity",
      "Microsoft.VSTS.Scheduling.Effort",
      "Microsoft.VSTS.Scheduling.RemainingWork",
      "Microsoft.VSTS.Build.FoundIn",
      "Microsoft.VSTS.Build.IntegrationBuild",
      "Microsoft.VSTS.TCM.ReproSteps",
      "Microsoft.VSTS.TCM.SystemInfo",
      "Microsoft.VSTS.Common.AcceptanceCriteria",
    ],
    Epic: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.Effort",
      "Microsoft.VSTS.Scheduling.StartDate",
      "Microsoft.VSTS.Build.IntegrationBuild",
      "Microsoft.VSTS.Common.TimeCriticality",
      "Microsoft.VSTS.Common.BusinessValue",
      "Microsoft.VSTS.Common.ValueArea",
      "Microsoft.VSTS.Common.AcceptanceCriteria",
    ],
    Feature: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.Effort",
      "Microsoft.VSTS.Scheduling.StartDate",
      "Microsoft.VSTS.Build.IntegrationBuild",
      "Microsoft.VSTS.Common.TimeCriticality",
      "Microsoft.VSTS.Common.BusinessValue",
      "Microsoft.VSTS.Common.ValueArea",
      "Microsoft.VSTS.Common.AcceptanceCriteria",
    ],
    Inpediment: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Resolution",
    ],
    "Product Backlog Item": [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.Effort",
      "Microsoft.VSTS.Common.BusinessValue",
      "Microsoft.VSTS.Common.ValueArea",
      "Microsoft.VSTS.Common.AcceptanceCriteria",
    ],
    Task: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Activity",
      "Microsoft.VSTS.CMMI.Blocked",
      "Microsoft.VSTS.Scheduling.RemainingWork",
    ],
    "Test Case": ["Microsoft.VSTS.TCM.ReproSteps"],
  },
  CMMI: {
    Bug: [
      "Microsoft.VSTS.Common.ResolvedReason",
      "Microsoft.VSTS.Scheduling.Size",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Triage",
      "Microsoft.VSTS.CMMI.Blocked",
      "Microsoft.VSTS.Scheduling.OriginalEstimate",
      "Microsoft.VSTS.Scheduling.RemainingWork",
      "Microsoft.VSTS.Scheduling.CompletedWork",
      "Microsoft.VSTS.Common.Discipline",
      "Microsoft.VSTS.CMMI.RootCause",
      "Microsoft.VSTS.TCM.ReproSteps",
      "Microsoft.VSTS.CMMI.Symptom",
      "Microsoft.VSTS.TCM.SystemInfo",
      "Microsoft.VSTS.CMMI.ProposedFix",
    ],
    "Change Request": [
      "Microsoft.VSTS.CMMI.Justification",
      "Microsoft.VSTS.CMMI.ImpactOnArchitecture",
      "Microsoft.VSTS.CMMI.ImpactOnUserExperience",
      "Microsoft.VSTS.CMMI.ImpactOnTest",
      "Microsoft.VSTS.CMMI.ImpactOnDevelopment",
      "Microsoft.VSTS.CMMI.ImpactOnTechnicalPublications",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Triage",
      "Microsoft.VSTS.CMMI.Blocked",
      "Integrated", //cant find
    ],
    Epic: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.StartDate",
      "Microsoft.VSTS.Scheduling.TargetDate",
      "Microsoft.VSTS.Common.Triage",
      "Microsoft.VSTS.Scheduling.Effort",
      "Microsoft.VSTS.Common.BusinessValue",
      "Microsoft.VSTS.Common.TimeCriticality",
      "Microsoft.VSTS.Common.ValueArea",
    ],
    Feature: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Scheduling.StartDate",
      "Microsoft.VSTS.Scheduling.TargetDate",
      "Microsoft.VSTS.Common.Triage",
      "Microsoft.VSTS.Scheduling.Effort",
      "Microsoft.VSTS.Common.BusinessValue",
      "Microsoft.VSTS.Common.TimeCriticality",
      "Microsoft.VSTS.Common.ValueArea",
    ],
    "Change request": [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Triage",
      "Microsoft.VSTS.CMMI.Escalate",
      "Microsoft.VSTS.Scheduling.OriginalEstimate",
      "Microsoft.VSTS.Scheduling.TargetDate",
      "Microsoft.VSTS.CMMI.TargetResolveDate",
    ],
    Requirement: [
      "Microsoft.VSTS.CMMI.ImpactAssessmentHtml",
      "Plan", //cant find either
      "Microsoft.VSTS.CMMI.CorrectiveActionActualResolution",
      "Microsoft.VSTS.Scheduling.Size",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Triage",
      "Microsoft.VSTS.CMMI.Blocked",
      "Microsoft.VSTS.CMMI.Committed",
    ],
    Risk: [
      "Microsoft.VSTS.CMMI.ContingencyPlan",
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Severity",
      "Microsoft.VSTS.CMMI.Blocked",
      "Microsoft.VSTS.Scheduling.OriginalEstimate",
      "Microsoft.VSTS.CMMI.Probability",
    ],
    Task: [
      "Microsoft.VSTS.Common.Priority",
      "Microsoft.VSTS.Common.Triage",
      "Microsoft.VSTS.CMMI.Blocked",
      "Microsoft.VSTS.Scheduling.OriginalEstimate",
      "Microsoft.VSTS.Scheduling.RemainingWork",
      "Microsoft.VSTS.Scheduling.CompletedWork",
    ],
    "Test Case": [
      "Microsoft.VSTS.TCM.ReproSteps",
      "Microsoft.VSTS.Scheduling.OriginalEstimate",
      "Microsoft.VSTS.Scheduling.RemainingWork",
      "Microsoft.VSTS.Scheduling.CompletedWork",
      "Microsoft.VSTS.Scheduling.StartDate",
      "Microsoft.VSTS.Scheduling.FinishDate",
    ],
  },
};

const newObj = {};

Object.keys(workItemFields1).forEach((process) => {
  newObj[process] = newObj[process] ?? {};
  Object.keys(workItemFields1[process]).forEach((field) => {
    newObj[process][field] = newObj[process][field] ?? [];
    workItemFields1[process][field].forEach((e, i) => {
      newObj[process][field].push({
        name: e,
        field: workItemFields2[process][field][i],
      });
    });
  });
});

fs.writeFileSync("a.js", JSON.stringify(newObj));
